-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-03-19 23:21:11 GMT-05:00
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



ALTER TABLE Evaluation 
    DROP CONSTRAINT Evaluation_Subject_FK 
;
ALTER TABLE Behavior_Catogory 
    DROP CONSTRAINT TABLE_12_Behaviors_FK 
;
ALTER TABLE Behavior_Catogory 
    DROP CONSTRAINT TABLE_12_Categories_FK 
;
ALTER TABLE Events 
    DROP CONSTRAINT TABLE_13_Person_FK 
;
ALTER TABLE Events 
    DROP CONSTRAINT TABLE_13_Subject_FK 
;
ALTER TABLE Subject_Behavior_presents 
    DROP CONSTRAINT TABLE_14_Behaviors_FK 
;
ALTER TABLE Subject_Behavior_presents 
    DROP CONSTRAINT TABLE_14_Evaluation_FK 
;
ALTER TABLE Subject_Behavior_presents 
    DROP CONSTRAINT TABLE_14_Person_FK 
;
ALTER TABLE Subject_Behavior_presents 
    DROP CONSTRAINT TABLE_14_Person_FKv1 
;
ALTER TABLE Subject_Behavior_presents 
    DROP CONSTRAINT TABLE_14_Subject_FK 
;
ALTER TABLE Evaluation 
    DROP CONSTRAINT TABLE_2_Person_FK 
;
ALTER TABLE Collection_Period 
    DROP CONSTRAINT TABLE_6_Evaluation_FK 
;
ALTER TABLE Collection_Period 
    DROP CONSTRAINT TABLE_6_Person_FK 
;
ALTER TABLE Collection_Period 
    DROP CONSTRAINT TABLE_6_Person_FKv1 
;
ALTER TABLE Collection_Period_Attendees 
    DROP CONSTRAINT TABLE_7_Evaluation_FK 
;
ALTER TABLE Collection_Period_Attendees 
    DROP CONSTRAINT TABLE_7_Person_FK 
;
ALTER TABLE Collection_Period_Attendees 
    DROP CONSTRAINT TABLE_7_Person_FKv1 
;
ALTER TABLE Collection_Period_Attendees 
    DROP CONSTRAINT TABLE_7_Person_FKv2 
;
ALTER TABLE Person_Collection_Period_Prompts 
    DROP CONSTRAINT TABLE_9_Evaluation_FK 
;
ALTER TABLE Person_Collection_Period_Prompts 
    DROP CONSTRAINT TABLE_9_Person_FK 
;
ALTER TABLE Person_Collection_Period_Prompts 
    DROP CONSTRAINT TABLE_9_Person_FKv1 
;
ALTER TABLE Person_Collection_Period_Prompts 
    DROP CONSTRAINT TABLE_9_Person_FKv2 
;
DROP TABLE Behavior_Catogory CASCADE CONSTRAINTS 
;
DROP TABLE Behaviors CASCADE CONSTRAINTS 
;
DROP TABLE Categories CASCADE CONSTRAINTS 
;
DROP TABLE Collection_Period CASCADE CONSTRAINTS 
;
DROP TABLE Collection_Period_Attendees CASCADE CONSTRAINTS 
;
DROP TABLE Evaluation CASCADE CONSTRAINTS 
;
DROP TABLE Events CASCADE CONSTRAINTS 
;
DROP TABLE Person CASCADE CONSTRAINTS 
;
DROP TABLE Person_Collection_Period_Prompts CASCADE CONSTRAINTS 
;
DROP TABLE Subject CASCADE CONSTRAINTS 
;
DROP TABLE Subject_Behavior_presents CASCADE CONSTRAINTS 
;

CREATE TABLE Behavior_Catogory 
    ( 
     category VARCHAR2 (20)  NOT NULL , 
     behavior VARCHAR2 (20)  NOT NULL 
    ) 
;





CREATE TABLE Behaviors 
    ( 
     name VARCHAR2 (20)  NOT NULL , 
     description VARCHAR2 (100) 
    ) 
;



ALTER TABLE Behaviors 
    ADD CONSTRAINT Behaviors_PK PRIMARY KEY ( name ) ;



CREATE TABLE Categories 
    ( 
     name VARCHAR2 (20)  NOT NULL , 
     description VARCHAR2 (100) 
    ) 
;



ALTER TABLE Categories 
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( name ) ;



CREATE TABLE Collection_Period 
    ( 
     "start" DATE , 
     end DATE , 
     collectorID INTEGER  NOT NULL , 
     therapistID INTEGER , 
     evalutationID INTEGER  NOT NULL 
    ) 
;





CREATE TABLE Collection_Period_Attendees 
    ( 
     personID INTEGER  NOT NULL , 
     evaluationID INTEGER  NOT NULL , 
     collectorID INTEGER  NOT NULL , 
     therapistID INTEGER  NOT NULL 
    ) 
;





CREATE TABLE Evaluation 
    ( 
     evaluationID INTEGER  NOT NULL , 
     "date" DATE , 
     location VARCHAR2 (20) , 
     analystID INTEGER  NOT NULL , 
     subjectSSN VARCHAR2 (10)  NOT NULL 
    ) 
;



ALTER TABLE Evaluation 
    ADD CONSTRAINT Evaluation_PK PRIMARY KEY ( evaluationID ) ;



CREATE TABLE Events 
    ( 
     eventID INTEGER  NOT NULL , 
     description VARCHAR2 (100) , 
     "date-time" DATE , 
     subjectSSN VARCHAR2 (10)  NOT NULL , 
     personID INTEGER  NOT NULL 
    ) 
;



ALTER TABLE Events 
    ADD CONSTRAINT Events_PK PRIMARY KEY ( eventID ) ;



CREATE TABLE Person 
    ( 
     personID INTEGER  NOT NULL , 
     name VARCHAR2 (20) 
    ) 
;



ALTER TABLE Person 
    ADD CONSTRAINT Person_PK PRIMARY KEY ( personID ) ;




--  ERROR: Table name length exceeds maximum allowed length(30) 
CREATE TABLE Person_Collection_Period_Prompts 
    ( 
     personID INTEGER  NOT NULL , 
     collectorID INTEGER  NOT NULL , 
     therapistID INTEGER  NOT NULL , 
     evaluationID INTEGER  NOT NULL , 
     duration DATE , 
     time TIMESTAMP (0) 
    ) 
;





CREATE TABLE Subject 
    ( 
     SubjectSSN VARCHAR2 (10)  NOT NULL , 
     personID INTEGER  NOT NULL , 
     DOB DATE  NOT NULL , 
     name VARCHAR2 (20) 
    ) 
;



ALTER TABLE Subject 
    ADD CONSTRAINT Subject_PK PRIMARY KEY ( SubjectSSN, personID ) ;



CREATE TABLE Subject_Behavior_presents 
    ( 
     duration INTEGER , 
     time DATE , 
     response VARCHAR2 (20) , 
     behavior VARCHAR2 (20)  NOT NULL , 
     subjectSSN VARCHAR2 (10)  NOT NULL , 
     collectorID INTEGER  NOT NULL , 
     therapistID INTEGER  NOT NULL , 
     evaluationID INTEGER  NOT NULL , 
     subjectPersonID INTEGER  NOT NULL 
    ) 
;






ALTER TABLE Evaluation 
    ADD CONSTRAINT Evaluation_Subject_FK FOREIGN KEY 
    ( 
     subjectSSN,
     analystID
    ) 
    REFERENCES Subject 
    ( 
     SubjectSSN,
     personID
    ) 
;



ALTER TABLE Behavior_Catogory 
    ADD CONSTRAINT TABLE_12_Behaviors_FK FOREIGN KEY 
    ( 
     behavior
    ) 
    REFERENCES Behaviors 
    ( 
     name
    ) 
;



ALTER TABLE Behavior_Catogory 
    ADD CONSTRAINT TABLE_12_Categories_FK FOREIGN KEY 
    ( 
     category
    ) 
    REFERENCES Categories 
    ( 
     name
    ) 
;



ALTER TABLE Events 
    ADD CONSTRAINT TABLE_13_Person_FK FOREIGN KEY 
    ( 
     personID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Events 
    ADD CONSTRAINT TABLE_13_Subject_FK FOREIGN KEY 
    ( 
     subjectSSN,
     personID
    ) 
    REFERENCES Subject 
    ( 
     SubjectSSN,
     personID
    ) 
;



ALTER TABLE Subject_Behavior_presents 
    ADD CONSTRAINT TABLE_14_Behaviors_FK FOREIGN KEY 
    ( 
     behavior
    ) 
    REFERENCES Behaviors 
    ( 
     name
    ) 
;



ALTER TABLE Subject_Behavior_presents 
    ADD CONSTRAINT TABLE_14_Evaluation_FK FOREIGN KEY 
    ( 
     evaluationID
    ) 
    REFERENCES Evaluation 
    ( 
     evaluationID
    ) 
;



ALTER TABLE Subject_Behavior_presents 
    ADD CONSTRAINT TABLE_14_Person_FK FOREIGN KEY 
    ( 
     therapistID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Subject_Behavior_presents 
    ADD CONSTRAINT TABLE_14_Person_FKv1 FOREIGN KEY 
    ( 
     collectorID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Subject_Behavior_presents 
    ADD CONSTRAINT TABLE_14_Subject_FK FOREIGN KEY 
    ( 
     subjectSSN,
     subjectPersonID
    ) 
    REFERENCES Subject 
    ( 
     SubjectSSN,
     personID
    ) 
;



ALTER TABLE Evaluation 
    ADD CONSTRAINT TABLE_2_Person_FK FOREIGN KEY 
    ( 
     analystID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Collection_Period 
    ADD CONSTRAINT TABLE_6_Evaluation_FK FOREIGN KEY 
    ( 
     evalutationID
    ) 
    REFERENCES Evaluation 
    ( 
     evaluationID
    ) 
;



ALTER TABLE Collection_Period 
    ADD CONSTRAINT TABLE_6_Person_FK FOREIGN KEY 
    ( 
     collectorID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Collection_Period 
    ADD CONSTRAINT TABLE_6_Person_FKv1 FOREIGN KEY 
    ( 
     therapistID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Collection_Period_Attendees 
    ADD CONSTRAINT TABLE_7_Evaluation_FK FOREIGN KEY 
    ( 
     evaluationID
    ) 
    REFERENCES Evaluation 
    ( 
     evaluationID
    ) 
;



ALTER TABLE Collection_Period_Attendees 
    ADD CONSTRAINT TABLE_7_Person_FK FOREIGN KEY 
    ( 
     personID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Collection_Period_Attendees 
    ADD CONSTRAINT TABLE_7_Person_FKv1 FOREIGN KEY 
    ( 
     collectorID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Collection_Period_Attendees 
    ADD CONSTRAINT TABLE_7_Person_FKv2 FOREIGN KEY 
    ( 
     therapistID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Person_Collection_Period_Prompts 
    ADD CONSTRAINT TABLE_9_Evaluation_FK FOREIGN KEY 
    ( 
     evaluationID
    ) 
    REFERENCES Evaluation 
    ( 
     evaluationID
    ) 
;



ALTER TABLE Person_Collection_Period_Prompts 
    ADD CONSTRAINT TABLE_9_Person_FK FOREIGN KEY 
    ( 
     personID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Person_Collection_Period_Prompts 
    ADD CONSTRAINT TABLE_9_Person_FKv1 FOREIGN KEY 
    ( 
     collectorID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;



ALTER TABLE Person_Collection_Period_Prompts 
    ADD CONSTRAINT TABLE_9_Person_FKv2 FOREIGN KEY 
    ( 
     therapistID
    ) 
    REFERENCES Person 
    ( 
     personID
    ) 
;
